# Generated by Django 5.1.1 on 2025-04-21 15:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('datacriacao', models.DateField(default=datetime.date.today)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('fotousuario', models.ImageField(blank=True, null=True, upload_to='fotoPerfilUsuario/')),
                ('datanascimento', models.DateField()),
                ('cidadenatal', models.CharField(max_length=50)),
                ('estadocivil', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PostsText',
            fields=[
                ('idPostText', models.AutoField(primary_key=True, serialize=False)),
                ('datapostagem', models.DateField(default=datetime.date.today)),
                ('descricao', models.TextField(max_length=255)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PostsFoto',
            fields=[
                ('idPost', models.AutoField(primary_key=True, serialize=False)),
                ('imagens', models.ImageField(blank=True, upload_to='fotosUsuarios/')),
                ('datapostagem', models.DateField(default=datetime.date.today)),
                ('descricao', models.TextField(max_length=255)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ComentariosPostsFoto',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False)),
                ('textComentado', models.TextField(max_length=255)),
                ('dataComentario', models.DateField(default=datetime.date.today)),
                ('idPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postsfoto')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioPostsText',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False)),
                ('textComentado', models.CharField(max_length=190)),
                ('dataComentario', models.DateField(default=datetime.date.today)),
                ('idPostText', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.poststext')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Amizades',
            fields=[
                ('idAmizade', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('idAmigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amizades_recebidas', to='app.usuario')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amizades_iniciadas', to='app.usuario')),
            ],
        ),
    ]
